import './globals.css'
import { Poppins } from "next/font/google";
import { TiWeatherCloudy } from "react-icons/ti";

const PoppinsBold = Poppins({ weight: "600", subsets: ["latin"] });
const PoppinsRegular = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`h-full bg-neutral-300 ${PoppinsRegular.className}`}>
        <div className="w-full p-5 flex gap-1 items-center">
          <TiWeatherCloudy size={"2em"} />
          <span className={`text-2xl ${PoppinsBold.className}`}>
            Weather App
          </span>
        </div>
        {children}
      </body>
    </html>
  );
}
